version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - DATABASE_URL=sqlite:///./data/job_matching.db
    volumes:
      # Mount database directory for persistence
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
      # Optional: Mount source code for development (comment out for production)
      # - ./src:/app/src
      # - ./main.py:/app/main.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  logs:
    driver: local